language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
  - php: hhvm


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/log
  - phpunit --coverage-clover=build/logs/clover.xml

after_script:

  #Scrutinzer CI
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

  #Coveralls
  - php bin/coveralls -p